import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
const out = resolve(import.meta.dirname, 'artifacts')
const a = JSON.parse(readFileSync(resolve(out, 'analysis.json')))
const review = JSON.parse(readFileSync(resolve(import.meta.dirname, 'review.json')))
const e = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const names = values => e(values.join(' · ') || 'Seçim yok')
const list = (label, values) => `<div><p class="label">${label}</p><p class="names">${names(values)}</p></div>`
const html = `<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Havuzun tamamı: isim kalitesi incelemesi</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#111418;color:#e6e9ed;font:16px/1.6 system-ui}main{max-width:1150px;margin:auto;padding:36px 24px}h1{font-size:32px;line-height:1.2;max-width:760px}h2{font-size:19px;line-height:1.4}h3{font-size:16px}p{margin:8px 0}.muted,.label{color:#aab5c3}.label{font-size:13px}.stats{display:flex;gap:24px;flex-wrap:wrap;border-block:1px solid #343d49;margin:24px 0;padding:16px 0}.stats strong{font-size:24px;display:block}.cols{display:grid;grid-template-columns:1fr 1fr;gap:24px}.names{font-size:21px;font-weight:600;overflow-wrap:anywhere}.picks{color:#b7d9ae}.brief{border-top:1px solid #343d49;padding:24px 0}.candidate{border-top:1px solid #29313b;padding:12px 0}.candidate h3{margin:0}.candidate[data-category=shortlist] h3{color:#b7d9ae}summary{cursor:pointer;padding:8px 0}details details{font-size:14px}.source{padding:8px 12px;background:#1a2028;margin:6px 0;overflow-wrap:anywhere}.controls{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}input,select{font:inherit;color:inherit;background:#1a2028;border:1px solid #566375;padding:8px 12px;border-radius:5px;max-width:100%}a{color:#b7cff2}code{overflow-wrap:anywhere}[hidden]{display:none!important}.notice{border-left:3px solid #ac9061;padding-left:16px}.inference{color:#d7bd93}@media(max-width:700px){main{padding:24px 16px}h1{font-size:27px}.cols{grid-template-columns:1fr;gap:8px}.stats{gap:16px}.stats strong{font-size:21px}}
.controls label{min-width:0;max-width:100%}select{width:100%}@media(max-width:700px){.controls label{width:100%}input{width:100%}}
</style><main>
<p class="label">NEOLOGISM ENGINE / HAVUZ İNCELEMESİ / TOHUM 13</p>
<h1>İyi adaylar nerede kayboluyor?</h1>
<p>170 uygun adayın tamamını okudum. Kısa listemdeki 21 seçimin 17'si zaten finalistlerde; dört alternatif aşağıda kalıyor. Token güvenliği için güçlü bir seçimim yok.</p>
<div class="stats"><div><strong>170</strong>incelenen aday</div><div><strong>21</strong>asistan seçimi</div><div><strong>4</strong>saklı alternatif</div><div><strong>2 / 2</strong>benimsenmeyen kural</div></div>
<p class="notice">Bu sayfa kaynakları görerek yaptığım editoryal inceleme. İnsan beğenisi, kör test veya kalite artışı kanıtı değil. Aynı isim farklı brieflerde ayrı sayılır. Yerel çakışma verisinde görünmemek güncel müsaitlik anlamına gelmez.</p>
<p><a href="../REPORT.md">Teknik rapor</a> · <a href="analysis.json">Tam izler ve karşılaştırma</a> · <a href="identity.json">Kaynak kimlikleri</a></p>
<details id="rules"><summary>İki basit düzeltme neden benimsenmedi?</summary><p>En az üç harf kuralı Macheck'i çıkarıyor ama Manicheck'i getiriyor; saklı seçimlerimin hiçbirini öne almıyor. Bir kaynak kelime tam kalsın kuralı Acticord'u çıkarıp Beaconcess'i getiriyor. Her ikisi de önceki 44 havuzda denendi, hiçbir ağırlık veya üretim malzemesi değiştirilmedi.</p><p>Görünen harf parçaları aşağıda eski kaynak kelimelerden yeniden kuruluyor. Bunlar özgün fonetik kesim kaydı veya ölçülmüş tanınabilirlik değil. Anlam bağlantısı, kelimenin ne kadarının okuyucuya geçtiğini tek başına söylemiyor.</p></details>
<div class="controls"><label>İsim ara <input id="search" type="search" placeholder="örn. Maniseal"></label><label>Havuz filtresi <select id="filter"><option value="all">Tüm uygun adaylar</option><option value="shortlist">Benim seçimlerim</option><option value="buried">Finalist olmayan seçimlerim</option>${Object.entries(review.categories).filter(([k])=>k!=='shortlist').map(([k,v])=>`<option value="${k}">${e(v)}</option>`).join('')}</select></label></div><p id="visible" class="muted" aria-live="polite"></p>
${a.rows.map((r,i)=>`<section class="brief"><h2>${i+1}. ${e(r.brief)}</h2><div class="cols">${list('MEVCUT LAB FİNALİSTLERİ',r.current)}<div class="picks">${list('BENİM KISA LİSTEM',r.picks)}</div></div><p>${e(r.rationale)}</p>${r.buried.length?`<p class="picks">Finalistlere ulaşmayan: ${names(r.buried)}</p>`:''}<details class="pool"><summary>Tüm uygun havuz · ${r.proposals.length} isim</summary>
${r.proposals.map(p=>`<article class="candidate" data-name="${e(p.name.toLowerCase())}" data-category="${p.category}" data-buried="${p.category==='shortlist'&&!p.selected}"><h3>${e(p.name)} ${p.selected?'· finalist':''}</h3><p>${e(review.categories[p.category])}</p><p class="label">Seçim izi: ${e(p.decision)} · ${e(p.collision)}</p><details><summary>Kaynak, sıra ve anlam kanıtı</summary>${p.sources.map(s=>`<div class="source"><strong>${e(s.family)} · sıra ${s.rank}</strong>${s.rejection?` · kaynak elendi: ${e(s.rejection)}`:''}<p>${s.meaning.map(l=>`${e(l.term)} → ${e(l.material)} (${e(l.method)})`).join('<br>')||'Anlam bağlantısı yok'}</p>${s.reason?`<p>Üreticide kayıtlı açıklama: ${e(s.reason.gloss)}</p>`:''}${s.inferredCuts.length?`<p class="inference">Yazımdan olası ayrım: ${s.inferredCuts.map(c=>`${e(c.prefix)} + ${e(c.suffix)} ← ${e(c.left)} + ${e(c.right)}`).join('; ')}</p>`:''}</div>`).join('')}</details></article>`).join('')}</details><details><summary>Sabit havuzdaki kural denemeleri</summary>${list('EN AZ ÜÇ HARF',r.variants.three_letters.finalists)}${list('EN AZ BİR TAM KAYNAK KELİME',r.variants.one_whole_parent.finalists)}<p class="muted">Üretime veya Lab'a alınmadı. Auto: ${names(r.auto)}</p></details></section>`).join('')}
<p>11 briefte bir seçim yapabilmem insan başarı eşiğinin karşılandığı anlamına gelmez. Özgün kapı: 8/12 galibiyet, en az altı kullanılabilir brief, Auto'ya göre en az üç brief artış, 3/4 tekrar tutarlılığı. Bekliyor.</p></main>
<script>const search=document.querySelector('#search'),filter=document.querySelector('#filter');function update(){let count=0;for(const c of document.querySelectorAll('.candidate')){const match=c.dataset.name.includes(search.value.trim().toLowerCase())&&(filter.value==='all'||filter.value===c.dataset.category||(filter.value==='buried'&&c.dataset.buried==='true'));c.hidden=!match;if(match)count++}for(const section of document.querySelectorAll('.brief')){const match=section.querySelector('.candidate:not([hidden])');section.hidden=!match;if((search.value||filter.value!=='all')&&match)section.querySelector('.pool').open=true}document.querySelector('#visible').textContent=count+' / 170 aday gösteriliyor'}search.addEventListener('input',update);filter.addEventListener('change',update);update();</script></html>`
writeFileSync(resolve(out,'index.html'),html)
console.log('Wrote 12 reviewed briefs and 170 individually classified candidates')
