import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { withBrowser } from '../shared-pool/harness.mjs'
const out=resolve(import.meta.dirname,'artifacts')
await withBrowser(async page=>{
  await page.setViewportSize({width:1280,height:1000})
  const errors=[]
  page.on('pageerror',e=>errors.push(String(e)))
  await page.getByRole('button',{name:/Open app/}).click()
  await page.getByRole('button',{name:/Brief intent/}).click()
  const ready=()=>page.waitForFunction(()=>document.querySelector('.candidate-lab')?.getAttribute('aria-busy')==='false'&&document.querySelector('.candidate-lab [role="status"]')?.textContent?.includes('distinct candidates'),null,{timeout:60000})
  const benefit=page.getByRole('checkbox',{name:/Use product benefits/})
  assert.equal(await benefit.isChecked(),false)
  await benefit.check()
  const retained=page.getByRole('checkbox',{name:/Check retained fragment/})
  assert.equal(await retained.isChecked(),false)
  await retained.check()
  const brief='a utility that checks manifest hashes before installation'
  await page.getByRole('textbox',{name:'Project brief'}).fill(brief)
  const storage=await page.evaluate(()=>JSON.stringify(localStorage))
  await page.getByRole('button',{name:'Generate',exact:true}).click();await ready()
  assert.match(await page.locator('.candidate-lab').innerText(),/Retained fragment check:/)
  const first=await page.locator('.finalist-name').allTextContents()
  assert(first.length>0&&first.length<=4)
  assert(!first.some(n=>n.toLowerCase()==='macheck'))
  await page.screenshot({path:resolve(out,'desktop.png'),fullPage:true})
  await page.locator('.finalist-list').screenshot({path:resolve(out,'finalists.png')})
  await page.getByRole('button',{name:/Show all/}).click()
  const row=page.locator('tbody tr').filter({has:page.getByRole('cell',{name:'Macheck',exact:true})})
  assert.match(await row.innerText(),/ma ← manifest \(unattested fragment\)/)
  await row.screenshot({path:resolve(out,'cut-evidence.png')})
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export experiment'}).click()
  await (await download).saveAs(resolve(out,'ui-export.json'))
  const exported=JSON.parse(readFileSync(resolve(out,'ui-export.json')))
  assert.equal(exported.run.config.variant,'retained_pool')
  assert(exported.run.semantic.check_retained_fragments)
  const m=exported.run.proposals.find(p=>p.id==='macheck').sources.find(s=>s.family==='seamblend')
  assert.equal(m.rejection,'unattested_fragment')
  assert.equal(m.semantic.retained_construction.parts[0].fragment,'ma')
  assert.equal(m.semantic.retained_construction.parts[0].source_end,2)
  await retained.uncheck()
  await page.getByRole('textbox',{name:'Project brief'}).fill('a different draft')
  await page.getByRole('button',{name:'Next finalists'}).click();await ready()
  await page.waitForFunction(first=>document.querySelector('.candidate-lab')?.getAttribute('aria-busy')==='false' && [...document.querySelectorAll('.finalist-name')].every(n=>!first.includes(n.textContent)),first,{timeout:60000})
  assert.match(await page.locator('.candidate-lab').innerText(),/Retained fragment check:/)
  assert((await page.locator('.finalist-name').allTextContents()).every(n=>!first.includes(n)))
  await page.getByRole('textbox',{name:'Project brief'}).fill(brief)
  await page.getByRole('button',{name:'Generate',exact:true}).click();await ready()
  await page.waitForFunction(()=>document.querySelector('.candidate-lab')?.getAttribute('aria-busy')==='false' && document.querySelector('.candidate-lab')?.textContent?.includes('Meaning first:') && !document.querySelector('.candidate-lab')?.textContent?.includes('Retained fragment check:'),null,{timeout:60000})
  assert(!(await page.locator('.candidate-lab').innerText()).includes('Retained fragment check:'))
  assert((await page.locator('.finalist-name').allTextContents()).some(n=>n.toLowerCase()==='macheck'))
  await retained.check()
  await page.getByRole('textbox',{name:'Project brief'}).fill('a tool that does not track users')
  await page.getByRole('button',{name:'Generate',exact:true}).click();await ready()
  await page.waitForFunction(()=>document.querySelector('.candidate-lab')?.getAttribute('aria-busy')==='false' && document.querySelector('.candidate-lab')?.textContent?.includes('Meaning first: unresolved'),null,{timeout:60000})
  assert.equal(await page.locator('.finalist').count(),0)
  assert(await page.getByRole('button',{name:'Next finalists'}).isDisabled())
  await page.getByRole('textbox',{name:'Project brief'}).fill('a tool that verifies archive signatures before extraction')
  await page.getByRole('button',{name:'Generate',exact:true}).click();await ready()
  await page.waitForFunction(()=>document.querySelector('.candidate-lab')?.getAttribute('aria-busy')==='false' && document.querySelector('.candidate-lab')?.textContent?.includes('Product: archive'),null,{timeout:60000})
  await page.getByRole('button',{name:/Show all/}).click()
  const sig=page.locator('tbody tr').filter({has:page.getByRole('cell',{name:'Sigproof',exact:true})})
  assert.match(await sig.innerText(),/sig ← signature \(attested fragment\)/)
  await sig.screenshot({path:resolve(out,'attested-evidence.png')})
  await page.setViewportSize({width:390,height:844})
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))
  await page.evaluate(()=>window.scrollTo(0,document.querySelector('.finalist').getBoundingClientRect().top+scrollY-90))
  await page.screenshot({path:resolve(out,'mobile.png')})
  assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),storage)
  await page.getByRole('button',{name:/^Auto/}).click()
  assert.equal(await page.locator('.candidate-lab').count(),0)
  assert.deepEqual(errors,[])
  writeFileSync(resolve(out,'ui-verification.json'),JSON.stringify({passed:true,checks:['default off','exact cut display','attested and unattested evidence','export','continuation snapshot','return to previous mode','unresolved brief','mobile overflow','saved preferences unchanged','return to Auto','page errors']},null,2))
  console.log('PASS retained fragment Lab interaction, export, continuation and mobile')
})
