import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { withBrowser, root } from '../shared-pool/harness.mjs'
const out = resolve(root, 'research/operation-object/artifacts')
await withBrowser(async (page) => {
  const errors = []
  page.on('pageerror', (e) => errors.push(String(e)))
  await page.getByRole('button', { name: /Open app/ }).click()
  await page.getByRole('button', { name: /Brief intent/ }).click()
  const checkbox = page.getByRole('checkbox', { name: /Require operation/ })
  assert.equal(await checkbox.isChecked(), false)
  await checkbox.check()
  const brief = 'a developer tool that verifies configuration files before deployment'
  await page.getByRole('textbox', { name: 'Project brief' }).fill(brief)
  const storage = await page.evaluate(() => JSON.stringify(localStorage))
  const ready = () => page.waitForFunction(() => document.querySelector('.candidate-lab')?.getAttribute('aria-busy') === 'false' && document.querySelector('.candidate-lab [role="status"]')?.textContent?.includes('distinct candidates'), null, { timeout: 60000 })
  await page.getByRole('button', { name: 'Generate', exact: true }).click()
  await ready()
  assert.match(await page.locator('.candidate-lab').innerText(), /verify → file/)
  const first = await page.locator('.finalist-name').allTextContents()
  await page.screenshot({ path: resolve(out, 'desktop.png'), fullPage: true, animations: 'disabled' })
  await checkbox.uncheck()
  assert.deepEqual(await page.locator('.finalist-name').allTextContents(), first, 'toggle only affects next Generate')
  if (first.length) {
    await page.locator('.candidate-lab').getByRole('button', { name: 'Keep', exact: true }).first().click()
    await page.getByRole('textbox', { name: 'Project brief' }).fill('a different draft')
    await page.getByRole('button', { name: 'Next finalists' }).click()
    await page.waitForFunction((names) => document.querySelector('.candidate-lab')?.getAttribute('aria-busy') === 'false'
      && [...document.querySelectorAll('.finalist-name')].every((node) => !names.includes(node.textContent)), first, { timeout: 60000 })
    assert((await page.locator('.finalist-name').allTextContents()).every((n) => !first.includes(n)))
  } else assert(await page.getByRole('button', { name: 'Next finalists' }).isDisabled())
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export experiment' }).click()
  await (await download).saveAs(resolve(out, 'ui-export.json'))
  const exported = JSON.parse(readFileSync(resolve(out, 'ui-export.json')))
  assert.equal(exported.run.config.description, brief)
  assert.equal(exported.run.config.variant, 'relation_pool')
  assert.equal(exported.run.relation.object_head.term, 'file')
  assert.equal(await page.evaluate(() => JSON.stringify(localStorage)), storage)
  // Main Generate follows the now-unchecked option and returns to original intent.
  await page.getByRole('textbox', { name: 'Project brief' }).fill(brief)
  await page.getByRole('button', { name: 'Generate', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.candidate-lab')?.getAttribute('aria-busy') === 'false'
    && document.querySelector('.candidate-lab [role="status"]')?.textContent?.includes('distinct candidates')
    && !document.querySelector('.candidate-lab')?.textContent?.includes('Operation–object check:'), null, { timeout: 60000 })
  assert(!(await page.locator('.candidate-lab').innerText()).includes('Operation–object check:'))
  await checkbox.check()
  await page.getByRole('textbox', { name: 'Project brief' }).fill('a tool that does not track users')
  await page.getByRole('button', { name: 'Generate', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.candidate-lab')?.getAttribute('aria-busy') === 'false'
    && document.querySelector('.candidate-lab')?.textContent?.includes('unresolved ('), null, { timeout: 60000 })
  assert.equal(await page.locator('.finalist').count(), 0)
  assert.match(await page.locator('.candidate-lab').innerText(), /unresolved/)
  await page.getByRole('button', { name: 'Inspect rejected pool' }).click()
  assert(await page.locator('.candidate-lab tbody tr').count() > 0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, document.querySelector('.candidate-lab').offsetTop - 12))
  await page.screenshot({ path: resolve(out, 'mobile-empty.png'), animations: 'disabled' })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1))
  await page.getByRole('button', { name: /^Auto/ }).click()
  assert.equal(await page.locator('.candidate-lab').count(), 0)
  assert.equal(await page.evaluate(() => JSON.stringify(localStorage)), storage)
  assert.deepEqual(errors, [])
  console.log('PASS relation toggle, role display, export, continuation snapshot, original intent, empty-pool inspection, mobile and saved-data isolation')
})
