// Original editorial associations. These are naming hypotheses, not preference labels.
export const domains = [
  {id:'migration',label:'Data migration and recovery',directions:[['passage','Move safely between states'],['recovery','Return to a usable state'],['continuity','Preserve what matters through change']]},
  {id:'jobs',label:'Background jobs and queues',directions:[['cadence','Coordinate work in time'],['handoff','Pass work between workers'],['retry','Give interrupted work another chance']]},
  {id:'observation',label:'Observability',directions:[['visibility','Make hidden behavior visible'],['evidence','Keep a readable record'],['measurement','Put behavior in perspective']]},
  {id:'verification',label:'Configuration and artifact verification',directions:[['integrity','Establish that something is intact'],['attestation','Carry evidence of authenticity'],['agreement','Check against an expected standard']]},
].map(d=>({...d,directions:d.directions.map(([id,benefit])=>({id,benefit}))}))
export const jobs = [
  {id:'migrate_data',domain:'migration',label:'Move data between versions or stores',object:'database state',operation:'migrate',directions:['passage','continuity'],phrases:['database migration','database migrations','schema migration','schema migrations','schema changes','data migration'],actions:['migrate','rehearse','upgrade','move'],objects:['database','databases','schema','schemas','sqlite','postgresql','data'],incompatible:['furniture','bird','birds']},
  {id:'recover_state',domain:'migration',label:'Recover an earlier usable state',object:'stored state',operation:'restore',directions:['recovery','continuity'],phrases:['database recovery','file recovery','archive recovery','state recovery','database rollback','backup restoration'],actions:['restore','recover','rollback','revert'],objects:['database','databases','archive','archives','file','files','configuration','session','state','snapshot','snapshots','replica'],incompatible:['furniture','antique','health']},
  {id:'schedule_jobs',domain:'jobs',label:'Coordinate queued or scheduled work',object:'background work',operation:'schedule',directions:['cadence','handoff'],phrases:['job scheduler','job scheduling','background jobs','background job','message queue client','queue client','task queue','worker pool'],actions:['schedule','dispatch','enqueue','coordinate','execute','process'],objects:['job','jobs','queue','queues','worker','workers','task','tasks','message','messages'],incompatible:['recruiter','recruiters','career','careers','appointment','appointments']},
  {id:'retry_delivery',domain:'jobs',label:'Retry or replay interrupted deliveries',object:'work delivery',operation:'retry',directions:['retry','handoff'],phrases:['webhook replay','webhook retries','delivery retries','job retries','retry queue'],actions:['retry','replay','redeliver','resume'],objects:['webhook','webhooks','delivery','deliveries','job','jobs','task','tasks','message','messages','queue'],incompatible:['meal','meals','parcel','parcels']},
  {id:'inspect_signals',domain:'observation',label:'Inspect and organize system signals',object:'system evidence',operation:'inspect',directions:['visibility','evidence'],phrases:['log viewer','log inspector','log explorer','log analysis','log aggregation','trace viewer','telemetry dashboard'],actions:['view','inspect','group','filter','sort','record','search','trace','analyze'],objects:['log','logs','trace','traces','telemetry','diagnostic','diagnostics','stacktrace','stacktraces'],incompatible:['football','weather','sports','medical']},
  {id:'measure_behavior',domain:'observation',label:'Observe and compare system behavior',object:'system behavior',operation:'measure',directions:['measurement','evidence','visibility'],phrases:['performance monitor','latency monitor','memory profiler','metrics dashboard','queue depth monitor','allocation profiler'],actions:['monitor','track','measure','compare','profile','inspect'],objects:['latency','memory','allocation','allocations','metrics','cpu','throughput','queue depth','performance','socket','sockets','connection','connections'],incompatible:['football','weather','sports','health']},
  {id:'verify_artifacts',domain:'verification',label:'Verify the integrity of an artifact',object:'artifact integrity',operation:'verify',directions:['integrity','attestation'],phrases:['checksum checker','signature verifier','artifact verification','checksum verification','signature verification','integrity checker'],actions:['verify','check','validate','compare'],objects:['checksum','checksums','signature','signatures','artifact','artifacts','hash','hashes','binary','binaries','manifest','manifests'],incompatible:['autograph','autographs','museum']},
  {id:'validate_config',domain:'verification',label:'Validate configuration against expectations',object:'configuration',operation:'validate',directions:['agreement','integrity'],phrases:['configuration validator','config validator','configuration validation','config validation','configuration checker','config checker'],actions:['validate','verify','check','lint'],objects:['configuration','configurations','config','configs','settings'],incompatible:['furniture','medical']},
]

// domain, direction, spelling, exact sense used, incompatible uses, optional
// second explicitly authored complete-word construction (no runtime clipping).
const material = [
  ['migration','passage','Waymark','a mark that guides a route','navigation hardware'],
  ['migration','passage','Causeway','a raised passage across difficult ground','road construction'],
  ['migration','passage','Crossing','a passage from one side to another','border administration'],
  ['migration','passage','Passage','a route from one place or state to another','travel booking'],
  ['migration','recovery','Reprise','a return to an earlier passage','music playback'],
  ['migration','recovery','Retrace','to follow a prior path back','route navigation'],
  ['migration','recovery','Keepsake','something retained to preserve a connection to the past','gift retail'],
  ['migration','recovery','Backtrack','to return along an earlier path','hiking navigation'],
  ['migration','continuity','Foothold','a secure place from which to make progress','climbing equipment'],
  ['migration','continuity','Lifeline','a connection that preserves continuity in difficulty','emergency response'],
  ['migration','continuity','Mainstay','a dependable source of support','sailing equipment'],
  ['migration','continuity','Continuum','a continuous sequence through changing states','physics simulation'],
  ['jobs','cadence','Cadence','a regular rhythm that coordinates activity','music notation'],
  ['jobs','cadence','Metronome','a device that keeps a regular beat','music practice'],
  ['jobs','cadence','Downbeat','the first beat that begins a measure','music criticism'],
  ['jobs','cadence','Roundabout','a circulating arrangement that coordinates passage','traffic planning'],
  ['jobs','handoff','Baton','an object passed between successive participants','sports equipment'],
  ['jobs','handoff','Relay','the passing of work from one participant to another','electrical hardware'],
  ['jobs','handoff','Tandem','participants arranged to work together','bicycle retail'],
  ['jobs','handoff','Turnstile','a mechanism that admits participants in sequence','access hardware'],
  ['jobs','retry','Encore','an additional performance after the first','concert booking'],
  ['jobs','retry','Reprise','a return to an earlier passage','music playback'],
  ['jobs','retry','Understudy','a prepared substitute that can take over a role','theater casting'],
  ['jobs','retry','Rebound','a return after an interruption or setback','sports coaching'],
  ['observation','visibility','Sightline','an unobstructed line along which something is visible','architectural planning'],
  ['observation','visibility','Lookout','a place or person from which to observe','security patrol'],
  ['observation','visibility','Fieldglass','an optical instrument for seeing distant details','optical retail'],
  ['observation','visibility','Aperture','an opening through which a view becomes possible','camera equipment'],
  ['observation','evidence','Logbook','an ordered record of observations and events','travel diary'],
  ['observation','evidence','Daybook','a chronological record of daily events','personal journaling'],
  ['observation','evidence','Witness','an observer whose account supplies evidence','legal testimony'],
  ['observation','evidence','Telltale','a sign that reveals something otherwise hidden','storytelling'],
  ['observation','measurement','Yardstick','a standard used to compare or measure','carpentry tools'],
  ['observation','measurement','Caliper','an instrument for comparing dimensions','manufacturing hardware'],
  ['observation','measurement','Parallax','a change in viewpoint that reveals relative position','astronomy education'],
  ['observation','measurement','Gauge','an instrument that makes a quantity legible','industrial hardware'],
  ['verification','integrity','Touchstone','a reference used to test quality or authenticity','jewelry testing'],
  ['verification','integrity','Assay','an examination used to determine composition or quality','medical diagnostics'],
  ['verification','integrity','Surety','a pledge that supports confidence in an obligation','insurance'],
  ['verification','integrity','Proof','evidence that establishes a claim','printing services',['Proofmark','proof','mark']],
  ['verification','attestation','Signet','a seal whose impression carries identity','jewelry retail'],
  ['verification','attestation','Watermark','an identifying mark carried within an artifact','image editing'],
  ['verification','attestation','Imprint','an impression left as evidence of an origin','publishing'],
  ['verification','attestation','Seal','a mark that attests to a state or origin','marine biology',['Sealscript','seal','script']],
  ['verification','agreement','Accord','agreement between things expected to correspond','automotive sales'],
  ['verification','agreement','Criterion','a standard by which something is judged','film distribution'],
  ['verification','agreement','Stipulate','to state a condition that must be satisfied','contract drafting'],
  ['verification','agreement','Concord','a state of agreement or correspondence','travel booking'],
]
const lexicalCompounds={Waymark:['way','mark'],Sightline:['sight','line'],Fieldglass:['field','glass'],Daybook:['day','book']}
export const entries=material.map(([domain,direction,name,sense,incompatible,second],rank)=>({
  id:`${domain}-${name.toLowerCase()}`,domain,direction,rank:rank+1,sense,
  suitable:[jobs.filter(j=>j.domain===domain&&j.directions.includes(direction)).map(j=>j.label).join('; ')],
  incompatible:[incompatible],source:'original-editorial-concept-naming-v1; not preference-validated',
  forms:[{name,kind:'whole_lexeme',components:lexicalCompounds[name]??[name.toLowerCase()]},...(second?[{name:second[0],kind:'complete_compound',components:second.slice(1)}]:[])],
}))
