import assert from 'node:assert/strict'
import { readFileSync,writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { withBrowser } from '../shared-pool/harness.mjs'
const out=resolve(import.meta.dirname,'artifacts')
await withBrowser(async page=>{
  const errors=[];page.on('pageerror',e=>errors.push(String(e)))
  await page.setViewportSize({width:1280,height:1000})
  await page.getByRole('button',{name:/Open app/}).click()
  await page.getByRole('button',{name:/Product names/}).click()
  assert.equal(await page.getByRole('button',{name:/Creativity:/}).count(),0)
  const input=page.getByRole('textbox',{name:'Project brief'})
  const ready=()=>page.waitForFunction(()=>document.querySelector('.product-names-lab')?.getAttribute('aria-busy')==='false'&&document.querySelector('.product-names-lab [role="status"]')?.textContent?.includes('distinct names'))
  const gen=async brief=>{await input.fill(brief);await page.getByRole('button',{name:'Generate',exact:true}).click();await ready();await page.waitForFunction(brief=>document.querySelector('.product-names-lab')?.getAttribute('data-brief')===brief&&document.querySelector('.product-names-lab')?.getAttribute('aria-busy')==='false',brief)}
  const storage=await page.evaluate(()=>JSON.stringify(localStorage))
  await gen('a terminal log viewer')
  const first=await page.locator('.finalist-name').allTextContents();assert(first.length>0&&first.length<=4)
  assert.equal(await page.locator('.finalist-score').count(),0)
  assert(!(await page.locator('.product-names-lab').innerText()).includes('npm install'))
  assert.match(await page.locator('.product-names-lab').innerText(),/availability unverified/)
  await page.getByRole('button',{name:'Keep',exact:true}).first().click()
  await page.screenshot({path:resolve(out,'desktop.png'),fullPage:true})
  await page.locator('.finalist-list').screenshot({path:resolve(out,'finalists.png')})
  await input.fill('a different unsent draft')
  await page.getByRole('button',{name:'Next finalists'}).click();await ready()
  assert((await page.locator('.finalist-name').allTextContents()).every(n=>!first.includes(n)))
  assert.match(await page.locator('.product-names-lab').innerText(),/Inspect and organize system signals/)
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export experiment'}).click()
  await(await download).saveAs(resolve(out,'ui-export.json'))
  const exported=JSON.parse(readFileSync(resolve(out,'ui-export.json')))
  assert.equal(exported.runs.length,2);assert.equal(exported.runs[1].request.config.description,'a terminal log viewer')
  assert.equal(exported.runs[0].data_identity,exported.runs[1].data_identity)
  assert.equal(Object.values(exported.sessionChoices).filter(x=>x==='keep').length,1)
  await gen('a tool that does not restore files')
  assert.equal(await page.locator('.finalist').count(),0)
  await page.getByRole('combobox',{name:'Product interpretation'}).selectOption('recover_state');await ready()
  assert.match(await page.locator('.product-names-lab').innerText(),/Selected by you/)
  assert(await page.locator('.finalist').count())
  await gen('a terminal log viewer')
  await page.getByRole('button',{name:'Keep a readable record',exact:true}).click();await ready()
  const focused=await page.locator('.finalist-name').allTextContents()
  assert(focused.length)
  await page.getByRole('button',{name:/Show all/}).click()
  assert(await page.locator('tbody tr').count())
  await page.getByRole('button',{name:'Next finalists'}).click();await ready()
  assert.equal(await page.locator('.finalist').count(),0)
  assert.match(await page.locator('.product-names-lab').innerText(),/No further eligible names/)
  await gen('a tool that verifies checksums')
  await page.setViewportSize({width:390,height:844})
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))
  await page.locator('.product-names-lab').scrollIntoViewIfNeeded()
  await page.waitForFunction(()=>[...document.querySelectorAll('.finalist')].every(e=>Number(getComputedStyle(e).opacity)>.99))
  await page.screenshot({path:resolve(out,'mobile.png'),fullPage:true})
  await gen('a community chat app')
  assert.equal(await page.locator('.finalist').count(),0)
  assert.match(await page.locator('.product-names-lab').innerText(),/does not match a supported product job/)
  await page.getByRole('button',{name:/^Auto/}).click()
  assert.equal(await page.locator('.product-names-lab').count(),0)
  assert.equal(await page.evaluate(()=>JSON.stringify(localStorage)),storage)
  assert.deepEqual(errors,[])
  writeFileSync(resolve(out,'ui-verification.json'),JSON.stringify({passed:true,checks:['new mode','no inactive creativity control','real finalist cards','product usage examples','scoped snapshot labels','session choices/export','immutable continuation','explicit interpretation correction','direction focus','exhaustion','mobile overflow','unsupported brief','saved preferences unchanged','return to Auto','page errors']},null,2)+'\n')
  console.log('PASS Product names Lab UI, continuation, interpretation, export, mobile and storage')
})
